import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import RootProvider from "@/components/providers/root-provider";

import "@/styles/globals.css";

const aspekta = localFont({
  src: [
    {
      path: "../public/fonts/Aspekta-350.woff2",
      weight: "350",
      style: "normal",
    },
    {
      path: "../public/fonts/Aspekta-550.woff2",
      weight: "550",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(aspekta.className, "font-sans")}
      suppressHydrationWarning
    >
      <body>
        <RootProvider>
          <main className="w-screen h-screen">{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
